//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace polowijo.gosari.timbangan.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_BAHAN_BAKU
    {
        public SO_BAHAN_BAKU()
        {
            this.SO_BAHAN_BAKU_DETAILS = new HashSet<SO_BAHAN_BAKU_DETAILS>();
        }
    
        public int ID { get; set; }
        public System.DateTime TANGGAL { get; set; }
        public string DOC_NUMBER { get; set; }
        public byte STATUS { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    
        public virtual ICollection<SO_BAHAN_BAKU_DETAILS> SO_BAHAN_BAKU_DETAILS { get; set; }
    }
}
