//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace polowijo.gosari.timbangan.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TOTAL_KIRIM
    {
        public string NO_SPB { get; set; }
        public int NO_DO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
